"""EDA (Exploratory Data Analysis) operations registry."""

import numpy as np
import pandas as pd

from agentic_patterns.mcp.data_analysis.display import df2str
from agentic_patterns.mcp.data_analysis.models import OperationConfig

EDA_OPERATIONS = {
    "head": OperationConfig(
        name="head",
        category="eda",
        func=lambda df, n=5: df2str(df.head(n), max_rows=n),
        parameters={"n": 5},
        returns_df=False,
        view_only=True,
        description="Display the first n rows of a dataframe",
    ),
    "tail": OperationConfig(
        name="tail",
        category="eda",
        func=lambda df, n=5: df2str(df.tail(n), max_rows=n),
        parameters={"n": 5},
        returns_df=False,
        view_only=True,
        description="Display the last n rows of a dataframe",
    ),
    "shape": OperationConfig(
        name="shape",
        category="eda",
        func=lambda df: {"rows": df.shape[0], "columns": df.shape[1]},
        parameters={},
        returns_df=False,
        view_only=True,
        description="Get the shape (dimensions) of a dataframe",
    ),
    "describe": OperationConfig(
        name="describe",
        category="eda",
        func=lambda df, include="all": df.describe(include=include).to_string(),
        parameters={"include": "all"},
        returns_df=False,
        view_only=True,
        description="Statistical summary of numeric columns",
    ),
    "info": OperationConfig(
        name="info",
        category="eda",
        func=lambda df: {
            "shape": {"rows": df.shape[0], "columns": df.shape[1]},
            "columns": df.columns.tolist(),
            "dtypes": {col: str(dtype) for col, dtype in df.dtypes.to_dict().items()},
            "null_counts": df.isnull().sum().to_dict(),
            "memory_usage": df.memory_usage(deep=True).to_dict(),
        },
        parameters={},
        returns_df=False,
        view_only=True,
        description="DataFrame information including types and null counts",
    ),
    "dtypes": OperationConfig(
        name="dtypes",
        category="eda",
        func=lambda df: {col: str(dtype) for col, dtype in df.dtypes.to_dict().items()},
        parameters={},
        returns_df=False,
        view_only=True,
        description="Data types of all columns",
    ),
    "columns": OperationConfig(
        name="columns",
        category="eda",
        func=lambda df: df.columns.tolist(),
        parameters={},
        returns_df=False,
        view_only=True,
        description="List all column names",
    ),
    "unique": OperationConfig(
        name="unique",
        category="eda",
        func=lambda df, column: df[column].unique().tolist(),
        parameters={"column": str},
        returns_df=False,
        view_only=True,
        description="Get unique values in a column",
    ),
    "nunique": OperationConfig(
        name="nunique",
        category="eda",
        func=lambda df, column=None: df[column].nunique() if column else df.nunique().to_dict(),
        parameters={"column": None},
        returns_df=False,
        view_only=True,
        description="Count unique values in columns",
    ),
    "value_counts": OperationConfig(
        name="value_counts",
        category="eda",
        func=lambda df, column, normalize=False: df[column].value_counts(normalize=normalize).reset_index(),
        parameters={"column": str, "normalize": False},
        returns_df=True,
        view_only=True,
        description="Value counts for a column",
    ),
    "correlation": OperationConfig(
        name="correlation",
        category="eda",
        func=lambda df, method="pearson", numeric_only=True: df.select_dtypes(include=[np.number]).corr(method=method) if numeric_only else df.corr(method=method),
        parameters={"method": "pearson", "numeric_only": True},
        returns_df=False,
        view_only=True,
        description="Correlation matrix between numeric columns",
    ),
    "missing_values": OperationConfig(
        name="missing_values",
        category="eda",
        func=lambda df: {
            "total_missing": df.isnull().sum().to_dict(),
            "percent_missing": (df.isnull().sum() / len(df) * 100).to_dict(),
        },
        parameters={},
        returns_df=False,
        view_only=True,
        description="Count and percentage of missing values per column",
    ),
    "groupby_mean": OperationConfig(
        name="groupby_mean",
        category="eda",
        func=lambda df, by: df.groupby(by).mean(numeric_only=True),
        parameters={"by": str},
        returns_df=True,
        view_only=False,
        description="Group by a column and calculate mean of numeric columns",
    ),
    "groupby_count": OperationConfig(
        name="groupby_count",
        category="eda",
        func=lambda df, by: df.groupby(by).size().to_frame("count"),
        parameters={"by": str},
        returns_df=True,
        view_only=False,
        description="Group by a column and count occurrences",
    ),
    "groupby_sum": OperationConfig(
        name="groupby_sum",
        category="eda",
        func=lambda df, by: df.groupby(by).sum(numeric_only=True),
        parameters={"by": str},
        returns_df=True,
        view_only=False,
        description="Group by a column and calculate sum of numeric columns",
    ),
    "pivot_table": OperationConfig(
        name="pivot_table",
        category="eda",
        func=lambda df, index, columns, values, aggfunc="mean": df.pivot_table(index=index, columns=columns, values=values, aggfunc=aggfunc),
        parameters={"index": str, "columns": str, "values": str, "aggfunc": "mean"},
        returns_df=True,
        view_only=False,
        description="Create a pivot table from the dataframe",
    ),
    "crosstab": OperationConfig(
        name="crosstab",
        category="eda",
        func=lambda df, index, columns, normalize=False: pd.crosstab(df[index], df[columns], normalize=normalize),
        parameters={"index": str, "columns": str, "normalize": False},
        returns_df=True,
        view_only=False,
        description="Create a cross-tabulation of two categorical variables",
    ),
}
