"""Strategy Protocol for vocabulary backends."""

from typing import Protocol, runtime_checkable

from agentic_patterns.core.connectors.vocabulary.models import (
    VocabularyInfo,
    VocabularyTerm,
)


@runtime_checkable
class Strategy(Protocol):
    """Protocol that all vocabulary strategy backends must satisfy."""

    def ancestors(
        self, term_code: str, max_depth: int = 10
    ) -> list[VocabularyTerm]: ...
    def children(self, term_code: str) -> list[VocabularyTerm]: ...
    def descendants(
        self, term_code: str, max_depth: int = 10
    ) -> list[VocabularyTerm]: ...
    def info(self) -> VocabularyInfo: ...
    def lookup(self, term_code: str) -> VocabularyTerm | None: ...
    def parent(self, term_code: str) -> list[VocabularyTerm]: ...
    def related(self, term_code: str, relation_type: str) -> list[VocabularyTerm]: ...
    def relationships(self, term_code: str) -> dict[str, list[str]]: ...
    def roots(self) -> list[VocabularyTerm]: ...
    def search(self, query: str, max_results: int = 10) -> list[VocabularyTerm]: ...
    def siblings(self, term_code: str) -> list[VocabularyTerm]: ...
    def subtree(self, term_code: str, max_depth: int = 3) -> list[VocabularyTerm]: ...
    def validate(self, term_code: str) -> tuple[bool, str | None]: ...
